config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'home#about'
  get '/pricing', to: 'home#pricing'

  resources :contacts, only: %i[new create]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { registrations: 'users/registrations' }

  namespace :account do
    root to: 'dashboard#index'
    resources :users
    resource  :profile, only: %i[show edit update]
    resources :device_groups, except: [:show]
    resources :devices, except:       [:show]
    resources :presentations
  end
end

app/views/shared/_flash.html.haml
- flash.each do |key, value|
  .flash-message
    %div{class: "alert alert-#{key}"}= value

app/views/shared/_footer.html.haml
%footer.navbar.footer
  .footer-container
    %span.list-item.col-sm-3
      = link_to "SpaceX", root_path
    .copyright.col-sm-5
      ©
      = Time.zone.now.year
      IF-097.Ruby.
      &nbsp
      = link_to "Terms of Service & Privacy Policy. ", "#", class: "rights"
      &nbsp
      All Rights Reserved.
    %ul.footer-list-social-media.col-sm-3
      %li.list-item Subscribe Us:
      %li.list-item
        = link_to "#" do
          = image_tag "twitter.png", class: "logo-social-media"
      %li.list-item
        = link_to "#" do
          = image_tag "facebook.png", class: "logo-social-media"
      %li.list-item
        = link_to "#" do
          = image_tag "instagram.png", class: "logo-social-media"

app/views/shared/_header.html.haml
%header.navbar.navbar-expand-lg.fixed-top
  = link_to root_path do
    .logo-motto
      = image_tag  "logo-pic.png", class: "logo-pic"
      %span SpaceX
  %nav.collapse.navbar-collapse
    %ul.navbar-nav.offset-md-2
      %li
        = link_to "Pricing", pricing_path , class: "nav-link"
      %li
        = link_to "About", about_path, class: "nav-link"
      %li
        = link_to "Contact Us", new_contact_path, class: "nav-link"
  .header-join
    - if user_signed_in?
      = link_to "Account", account_root_path, class: "header-join-account"
      .text-white
        or
      = link_to "Log Out", destroy_user_session_path, method: :delete, class: "header-join-log-out"
    - else
      = link_to "Join", new_user_registration_path, class: "header-join-sign-up"
      .text-white
        or
      = link_to "Log In", new_user_session_path, class: "header-join-log-in"