config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get '/about', to: 'home#about'
  get '/pricing', to: 'home#pricing'

  resources :contacts, only: %i[new create]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout' },
                     controllers: { registrations: 'users/registrations' }

  namespace :account do
    root to: 'dashboard#index'
    resources :users
    resource  :profile, only: %i[show edit update]
    resources :device_groups, except: [:show]
    resources :devices, except:       [:show]
    resources :presentations
  end
end

app/controllers/account/dashboard_controller.rb
class Account::DashboardController < ApplicationController
  before_action :authenticate_user!
  layout 'dashboard'

  def index; end
end

app/views/shared/dashboard/_footer.html.haml
.main-content
  %footer.footer
    %ul.list-inline
      %li 
      = Time.zone.now.year 
      © NinjaAdmin.
      %li
        %a{href: "#"} Privacy
      %li
        %a{href: "#"} Terms
      %li
        %a{href: "#"} Help

app/views/shared/dashboard/_header.html.haml
.fixed-navbar
  .pull-left
    %button.menu-mobile-button.glyphicon.glyphicon-menu-hamburger.js__menu_mobile{type: "button"}
    %h1.page-title Home
    / /.page-title
  / /.pull-left
  .pull-right
    .ico-item
      %a.ico-item.ti-search.js__toggle_open{"data-target": "#searchform-header", href: "#"}
      %form#searchform-header.searchform.js__toggle{action: "#"}
        %input.input-search{placeholder: "Search...", type: "search"}/
        %button.ti-search.button-search{type: "submit"}
      / /.searchform
    / /.ico-item
    %a.ico-item.ti-email.notice-alarm.js__toggle_open{"data-target": "#message-popup", href: "#"}
    %a.ico-item.ti-bell.notice-alarm.js__toggle_open{"data-target": "#notification-popup", href: "#"}
    .ico-item
      %i.ti-user
      %ul.sub-ico-item
        %li
          %a{href: "#"} Settings
        %li
          %a.js__logout
          = link_to('Log Out', destroy_user_session_path, method: :delete)
      / /.sub-ico-item
  / /.pull-right
/ /.fixed-navbar

app/views/shared/dashboard/_menu.html.haml
%body
  .main-menu
    %header.header
      = link_to root_path, class: "logo" do
        %i.ico.ti-rocket>
        SpaceX
      %button.button-close.fa.fa-times.js__menu_close{type: "button"}
    / /.header
    .content
      .navigation
        = link_to account_profile_path do
          - if current_user.avatar.attached?
            %img.mini-avatar{ src: "#{url_for(current_user.avatar)}" }
          - else
            %img.mini-user-icon{ src: "https://cdn1.iconfinder.com/data/icons/rcons-user-action/512/user-512.png"}
        Hello, #{current_user.first_name}!      
        %h5.title Navigation
        / /.title
        %ul.menu.js__accordion
          %li
            = link_to account_root_path do
              %i.menu-icon.ti-dashboard
              %span Dashboard
          %li
            = link_to account_profile_path do
              %i.menu-icon.ti-user
              %span Profile
          %li
            = link_to account_device_groups_path do
              %i.menu-icon.ti-desktop
              %span Device Groups
          %li
            = link_to account_presentations_path do
              %i.menu-icon.ti-layers-alt
              %span Presentations
          %li      
            = link_to account_devices_path do
              %i.menu-icon.ti-mobile
              %span Devices 
          - if current_user.admin?
            %li
              = link_to account_users_path do
                %i.menu-icon.ti-desktop
                %span Members